# fly.toml app configuration file generated for wbrms-food-delivery on 2023-10-16T11:57:28+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wbrms-food-delivery"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
